### ISSUE TITLE
LUA error when Tor uses his staff beam attack

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#10]
[ERROR] addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:33: attempt to index a nil value
  1. unknown - addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:33

[ERROR] addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:15: attempt to index a nil value
  1. unknown - addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:15

[ERROR] addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:42: attempt to perform arithmetic on field 'DieTime' (a nil value)
  1. unknown - addons/half-life-resurgence-master/lua/effects/vj_hlr_electric_charge/init.lua:42

**Comment by DrVrej** [comment]
I looked at the issue, and I realized Tor was never made. Somebody else must have made this SNPC and I never noticed. In this case, I will basically be deleting the SNPC and remaking it when the time comes.
