### ISSUE TITLE
Unknown Lua Error 

### ISSUE THREAD

**Issue by BrainDeadperson** [VJ-HLR-Developers/Half-Life-Resurgence#14]
This usually happens when a grunt is attacking a target, then it gets headcrabbed

Not always though, which is confusing

[ERROR] addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2294: attempt to index a nil value
  1. RunCode_OnFinish - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2294
   2. DoRunCode_OnFinish - addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:30
    3. ScheduleFinished - addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:101
     4. unknown - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2133

**Comment by DrVrej** [comment]
This happens in ZE only?

**Comment by BrainDeadperson** [comment]
Unsure, havent tried other mods but it appears commonly

**Comment by DrVrej** [comment]
Error has been detected to be part of the new human AI system in VJ Base, will fix this very soon.

**Comment by DrVrej** [comment]
Fixed in VJ Base
