### ISSUE TITLE
[HL:ZE] Enhacement, make it so if any ally sees a headcrab latch onto a nearby ally, they will try take the crab off, 50/50 chance of it.

### ISSUE THREAD

**Issue by BrainDeadperson** [VJ-HLR-Developers/Half-Life-Resurgence#15]
Just a small idea I came up with

**Comment by epicplayer40** [comment]
Doesn't seem like a nessessary enhancement. I'm only planning on adding features present in the original mod.

**Comment by DrVrej** [comment]
> Doesn't seem like a nessessary enhancement. I'm only planning on adding features present in the original mod.

If your not adding it, then close the issue
