### ISSUE TITLE
HL:ZE Enhancement

### ISSUE THREAD

**Issue by BrainDeadperson** [VJ-HLR-Developers/Half-Life-Resurgence#17]
Since the player cannot pick up headcrabs, such as they could in the original game

Make it so a zombie can hold a headcrab.
If they reach a scientist [only a scientist since they dont fight back]
it will shove them to the ground and place the headcrab on him

**Comment by epicplayer40** [comment]
Again, this doesn't seem like a nessessary enhancement. I'm only planning on adding features present in the original mod. This feature will require a lot more effort to implement.
