### ISSUE TITLE
[VJ-BASE] Unknown Lua Error

### ISSUE THREAD

**Issue by BrainDeadperson** [VJ-HLR-Developers/Half-Life-Resurgence#19]
When a HECU is reloading an error will sometimes pop up, this is what I got.

[ERROR] addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2261: attempt to call method 'NPC_ReloadWeapon' (a nil value)
  1. DoReloadAnimation - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2261
   2. RunCode_OnFinish - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:2297
    3. DoRunCode_OnFinish - addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:30
     4. StartSchedule - addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:87
      5. unknown - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:1348

**Comment by DrVrej** [comment]
Are you on latest VJ Base?

**Comment by DrVrej** [comment]
After testing, I conclude this error as invalid.
