### ISSUE TITLE
Rebels when they witness the death of an ally done by a player don't do anything

### ISSUE THREAD

**Issue by Lebert130** [VJ-HLR-Developers/Half-Life-Resurgence#2]
Not sure to call it a bug report or feature request but, when the player hits the rebels many times, their relationship changes, but when a rebel gets killed with a few hits (example: a crowbar), they don't react properly. This can be fixed by adding this piece of code in npc_vj_hlr2_rebel/init.lua down to ENT:CustomOnDoKilledEnemy:

    function ENT:CustomOnPriorToKilled(dmginfo, hitgroup)
    local allies = self:CheckAlliesAroundMe(checkdist)
        if allies != nil then
		for k, v in ipairs(allies) do
			v:CustomOnAllyDeath(self)
			
			if (dmginfo:GetAttacker():IsPlayer() == true) then
			//Copied the code from human_base
				if v:Disposition(dmginfo:GetAttacker()) != D_HT then
					v:CustomWhenBecomingEnemyTowardsPlayer(dmginfo,hitgroup)
					if v.FollowingPlayer == true && v.FollowPlayer_Entity == dmginfo:GetAttacker() then v:FollowPlayerReset() end
					v.VJ_AddCertainEntityAsEnemy[#self.VJ_AddCertainEntityAsEnemy+1] = dmginfo:GetAttacker()
					v:AddEntityRelationship(dmginfo:GetAttacker(),D_HT,99)
					v.TakingCoverT = CurTime() + 2
					if !IsValid(v:GetEnemy()) then
						v:StopMoving()
						v:SetTarget(dmginfo:GetAttacker())
						v:VJ_TASK_FACE_X("TASK_FACE_TARGET")
					end
					if v.AllowPrintingInChat == true then
						dmginfo:GetAttacker():PrintMessage(HUD_PRINTTALK, self:GetName().." no longer likes you.")
					end
					v:BecomeEnemyToPlayerSoundCode()
				end
				v.Alerted = true
			//
			end
		end
	end 
    end

What it does is when a rebel gets killed by a player, all the rebels around the rebel killed get notified and change their relationship towards the player.

Any improvements to the code are welcome.

**Comment by DrVrej** [comment]
Added!
