### ISSUE TITLE
Bullet Ricochette Effect Appearing at Map Origin On SNPC Melee

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#20]
If the bullet ricochette effect is triggered when an enemy SNPC is using a melee attack (e.g when a zombie attacks a robo grunt), the effect of the bullet ricochette will appear at the map's origin.

**Comment by DrVrej** [comment]
Cpt coded that part of the addon, I will go through it and see what is wrong with his code, if needed, I'll just recode it.

**Comment by DrVrej** [comment]
Latest commit fixes this issue for all SNPCs that use this effect.
