### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by xDShot** [VJ-HLR-Developers/Half-Life-Resurgence#21]
License is GNU AGPL, but there are headers in code:
```
/*-----------------------------------------------
	*** Copyright (c) 2012-2020 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted,
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
-----------------------------------------------*/
```

**Comment by DrVrej** [comment]
Thank you for the notice, the license in this repository is a placeholder. This repository is created for people to beta test, nothing here is permanent, including the repository itself. The one that matters is the final version that will be uploaded ok the Steam Workshop. Until then feel free to beta test, report any bugs and pull requests are welcomed! I will remove the GitHub license file as it serves no purpose.

**Comment by DrVrej** [comment]
License removed
