### ISSUE TITLE
all the hostiles npcs from half life 1 are just script error and dont attack

### ISSUE THREAD

**Issue by javierlovessylvie** [VJ-HLR-Developers/Half-Life-Resurgence#22]
ok so basically i tested this addon cuz i really like it but when i spawned the grunts they just run away from me and dont attack it also happens when they should attack other npcs this is the error that appears: [ERROR] addons/vj-base/lua/entities/npc_vj_creature_base/init.lua:1978: attempt to call method 'SetIdealYawAndUpdate' (a nil value)
  1. unknown - addons/vj-base/lua/entities/npc_vj_creature_base/init.lua:1978 i would be very thankful if u help me btw: yes i have the latest vj base version

**Comment by DrVrej** [comment]
Read the description, or even just look at your console, or even better, listen to the GMod devs. Stop using chromium branch.

**Comment by javierlovessylvie** [comment]
how to deactive chromium branch on non steam gmod

**Comment by Mawskeeto1223** [comment]
> 
> 
> how to deactive chromium branch on non steam gmod

stop using pirated GMod and buy the game. your version is outdated.
