### ISSUE TITLE
HD Branch Missing NPCS

### ISSUE THREAD

**Issue by Concon1231** [VJ-HLR-Developers/Half-Life-Resurgence#24]
All of the NPCS with a spawn icon made with Half-Life Model Viewer (blue background) have missing models and cannot be spawned. I am not sure if I didn't install the HD Branch correctly or what. Here's an example of what the icons I'm talking about look like.
![npc_vj_hlr1_scientist_hd](https://user-images.githubusercontent.com/72584590/95528451-c8e68c80-099d-11eb-931a-f8acf581020b.PNG)

**Comment by Cpt-Hazama** [comment]
This """issue""" has been addressed multiple times. They're obviously not made as they don't even have in-game icons...

**Comment by Concon1231** [comment]
> This """issue""" has been addressed multiple times. They're obviously not made as they don't even have in-game icons...

I'm sorry, I only got this mod a few days ago so I haven't really seen the development of this.
