### ISSUE TITLE
barnacle hl1 causes crashes

### ISSUE THREAD

**Issue by javierlovessylvie** [VJ-HLR-Developers/Half-Life-Resurgence#25]
ok so its me again i finnaly buyed gmod from steam and i been testing half life resurgence like for a month or more and i can say its the best addon eva but when i kill a barnacle that grabbed me or grabbed other npcs my game freezes and crashes idk why this happens but i think i can live with it btw: will u add barnacle grabbed animations to scientist grunts guards and alien slaves? hope to not make so much conflict thank you :)

**Comment by Cpt-Hazama** [comment]
The crashing issue exists in every VJ NPC that gibs (its more common in HLR), we are aware of it and are in the process of fixing it. It _should_ be fixed before release. As for the animations those are planned to be made before release as well.
