### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Deimos1020** [VJ-HLR-Developers/Half-Life-Resurgence#26]
When I play as a sniper combine, then for some reason I am attacked by combines and also with other hostile NPCs.
When an NPC from half life 2 is at war, there may be an animation bug. he will stand but the animation is like he is running.
When you control the NPC, then you are not treated by medic.

**Comment by Deimos1020** [comment]
> when I play as a sniper combine, then for some reason I am attacked by combines and also with other hostile NPCs.
When an NPC from half life 2 is at war, there may be an animation bug. he will stand but the animation is like he is running.
When you control the NPC, then you are not treated by medic.

**Comment by DrVrej** [comment]
Sadly this issue isn't fixable, it's caused by GMod itself, same models can't have proper relationship values set to them.
