### ISSUE TITLE
LUA error on Baby Gargantua footsteps

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#3]
`[ERROR] addons/half-life-resurgence-master/lua/entities/npc_vj_hlr1_garg/init.lua:100: attempt to call method 'WorldShakeOnMoveCode' (a nil value)
  1. CustomOnAcceptInput - addons/half-life-resurgence-master/lua/entities/npc_vj_hlr1_garg/init.lua:100
   2. unknown - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:2118`

**Comment by epicplayer40** [comment]
This error also occurs for the regular-sized Gargantua

**Comment by DrVrej** [comment]
Fixed.
