### ISSUE TITLE
LUA error when attacking a jumping female assassin

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#4]
When shooting a female assassin mid-air, this error occurs:

` [ERROR] addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:80: bad argument #1 to 'SetArrivalActivity' (number expected, got boolean)
  1. SetArrivalActivity - [C]:-1
   2. StartSchedule - addons/vj-base-master/lua/entities/npc_vj_human_base/schedules.lua:80
    3. VJ_TASK_COVER_FROM_ENEMY - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:1419
     4. unknown - addons/vj-base-master/lua/entities/npc_vj_human_base/init.lua:3877

 `

**Comment by epicplayer40** [comment]
Correction: This issue occurs when the assassin has landed and starts performing the land animation.

**Comment by DrVrej** [comment]
Has been fixed in the latest VJ Base commit
