### ISSUE TITLE
Father Grigori missing healing animation and sound

### ISSUE THREAD

**Issue by BreavyTF2** [VJ-HLR-Developers/Half-Life-Resurgence#41]
Father Grigori has a Healing animation and a sound unused, why aren't these used in the pack when making him a healer?

**Comment by DrVrej** [comment]
1. Post the unused sound, there is over 10,000 sounds in HLR, you are going to have to provide the sound path.
2. What animation and since when is Father Grigori a medic?

**Comment by BreavyTF2** [comment]
"vo/ravenholm/monk_givehealth01.wav"
"heal" 
Father Grigori reuses some citizen animations and also has a  giveammo sound as well.

**Comment by DrVrej** [comment]
Alright thanks for the suggestion, the way you worded is as if these were expected to be included, so you confused me. This isn't a bug report as such behavior for father Grigori was never planned, this is a suggestion.

**Comment by DrVrej** [comment]
We have come to the conclusion that we don't want to add such ability to the Father Grigori, healing will be left to the rebel medics only
