### ISSUE TITLE
A serious bad error

### ISSUE THREAD

**Issue by Sprosenax** [VJ-HLR-Developers/Half-Life-Resurgence#43]
[half-life-resurgence-master] addons/half-life-resurgence-master/lua/autorun/vj_hlr_autorun.lua:22: attempt to call field 'AddCategoryInfo' (a nil value)
  1. unknown - addons/half-life-resurgence-master/lua/autorun/vj_hlr_autorun.lua:22

why it happens (it can't appear in VJ Base)

**Comment by DrVrej** [comment]
This is an invalid report, it's your fault for using a very old version of VJ Base.

**Comment by Sprosenax** [comment]
What? i'm using latest version i updated it 20~ min ago!

**Comment by DrVrej** [comment]
> What? i'm using latest version i updated it 20~ min ago!
> 

You aren't, simple look at the error specifically tells you it's missing the function, therefore you are on an outdated version.
