### ISSUE TITLE
LUA error when Overwatch Engineer is shooting.

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#5]
ERROR] addons/half-life-resurgence-hlr_hl2/lua/weapons/weapon_vj_hlr2_reager/shared.lua:109: attempt to index field 'Loop' (a nil value)
  1. CustomOnRemove - addons/half-life-resurgence-hlr_hl2/lua/weapons/weapon_vj_hlr2_reager/shared.lua:109
   2. unknown - addons/vj-base-master/lua/weapons/weapon_vj_base/shared.lua:749
    3. Spawn - [C]:-1
     4. InternalSpawnNPC - gamemodes/sandbox/gamemode/commands.lua:452
      5. Spawn_NPC - gamemodes/sandbox/gamemode/commands.lua:505
       6. unknown - gamemodes/sandbox/gamemode/commands.lua:535
        7. unknown - lua/includes/modules/concommand.lua:54

There's also a missing particle:
Attempting to create unknown particle system 'electrical_arc_01'

**Comment by DrVrej** [comment]
I have recoded the whole entity, particle bug is confirmed fixed and the firing error should also be fixed.
