### ISSUE TITLE
i get this error everytime the probe droid shoots something 

### ISSUE THREAD

**Issue by Loganm2007** [VJ-HLR-Developers/Half-Life-Resurgence#52]
[half-life-resurgence-master] addons/half-life-resurgence-master/lua/entities/obj_vj_hlr1_probed_needle.lua:84: attempt to call global 'VJ_ApplySpeedEffect' (a nil value)
  1. CustomOnDoDamage - addons/half-life-resurgence-master/lua/entities/obj_vj_hlr1_probed_needle.lua:84
   2. DoDamageCode - lua/entities/obj_vj_projectile_base/init.lua:213
    3. unknown - lua/entities/obj_vj_projectile_base/init.lua:223

**Comment by DrVrej** [comment]
HLR requires, latest dev version of VJ Base and GMod.
