### ISSUE TITLE
abrams tank invisible glitch and gib error

### ISSUE THREAD

**Issue by javierlovessylvie** [VJ-HLR-Developers/Half-Life-Resurgence#55]
first of all hello thanks for reading i been having a recent issues since this days its that the m1a1 abrams npc when i get up of it for some reason turns invisble of the down part the npc stills perfectly functional but it makes kinda hard to see (watch 1st image) and the second is the most weird it consist that everytime the tank dies it gibs but recently the gibs get stuck in the superior part of the prop and cause a inmense lag that doesnt allow to me to make anything till y do an admin cleanup i dont know why this happens it only happens to the abrams the bradley continues perfect [
![gm_hl1_lily_construct_130193](https://user-images.githubusercontent.com/69820049/110391944-d166f000-802d-11eb-9470-a5acb93abae4.jpg)
![gm_hl1_lily_construct_130191](https://user-images.githubusercontent.com/69820049/110391961-d6c43a80-802d-11eb-9b75-3bfaee588698.jpg)

](url)

**Comment by DiscoChaoz** [comment]
what

**Comment by DrVrej** [comment]
Works completely fine on my end. Also the NPC going invisible is part of Source engine itself, if you manage to get inside an NPC's hitbox, they become invisible.
