### ISSUE TITLE
i need help setting up the mod

### ISSUE THREAD

**Issue by Jaycey64** [VJ-HLR-Developers/Half-Life-Resurgence#58]
guys, i need help, DO NOT CLOSE THIS ISSUE IDK HOW TO SET THIS UP I DOWNLOADED it and please DO NOT CLOSE THIS just please link me to something that can help me please and thank you.

**Comment by IvanVladimir04** [comment]
no

**Comment by DiscoChaoz** [comment]
no

**Comment by DrVrej** [comment]
This is ridiculous, you completely ignored my comment from your last post.
