### ISSUE TITLE
portal (race x) and portal (xen) fix

### ISSUE THREAD

**Issue by korplus** [VJ-HLR-Developers/Half-Life-Resurgence#59]
when i spawned them they dont spawned

**Comment by IvanVladimir04** [comment]
Thx for the debugging help

**Comment by Cpt-Hazama** [comment]
*sigh* Read your in-game chat

**Comment by korplus** [comment]
> _sigh_ Read your in-game chat

where

**Comment by personguybutsmart** [comment]
they only spawn when a player (in my experience ONLY a player) gets near them

**Comment by DrVrej** [comment]
> they only spawn when a player (in my experience ONLY a player) gets near them

It works fine on my end, when an enemy NPC approaches the area, the portal activates. This is assuming AI is enabled.
