### ISSUE TITLE
LUA error when a Hunter kills an enemy while continuously shooting.

### ISSUE THREAD

**Issue by epicplayer40** [VJ-HLR-Developers/Half-Life-Resurgence#6]
When a hunter kills the player and continues to shoot, this error is rapidly spewed in the console while the hunter continues firing flechettes with no velocity:

[ERROR] addons/half-life-resurgence-hlr_hl2/lua/entities/npc_vj_hlr2_com_hunter/init.lua:177: attempt to index a nil value
  1. RangeAttackCode_GetShootPos - addons/half-life-resurgence-hlr_hl2/lua/entities/npc_vj_hlr2_com_hunter/init.lua:177
   2. FireFlechette - addons/half-life-resurgence-hlr_hl2/lua/entities/npc_vj_hlr2_com_hunter/init.lua:135
    3. CustomOnThink - addons/half-life-resurgence-hlr_hl2/lua/entities/npc_vj_hlr2_com_hunter/init.lua:224
     4. unknown - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:2410

**Comment by DrVrej** [comment]
Hunter is no longer part of the official pack, so I will be closing this.
