### ISSUE TITLE
Kingpin spewing Lua errors

### ISSUE THREAD

**Issue by samrbrblxx** [VJ-HLR-Developers/Half-Life-Resurgence#61]
Everytime I spawn Kingpin, he spews Lua errors and refuses to attack at all. Unless it's some addon causing this problem or something else. 

[half-life-resurgence-master] addons/half-life-resurgence-master/lua/entities/npc_vj_hlr1_kingpin/init.lua:125: attempt to call method 'IsBusy' (a nil value)
  1. CustomAttack - addons/half-life-resurgence-master/lua/entities/npc_vj_hlr1_kingpin/init.lua:125
   2. unknown - lua/entities/npc_vj_creature_base/init.lua:1780 (x10)

**Comment by Cpt-Hazama** [comment]
You're supposed to be using the GitHub version of VJ Base.

Unreleased addon using new features ~= use workshop VJ Base
