### ISSUE TITLE
Apache machine gun bug

### ISSUE THREAD

**Issue by Combineadvisor** [VJ-HLR-Developers/Half-Life-Resurgence#62]
Whenever the apache uses its machine gun, It almost completely misses every shot on small targets such as players. I know its still very wip, just a heads up

**Comment by IvanVladimir04** [comment]
a

**Comment by DrVrej** [comment]
I will be basing the spread on the original apache from HL1, but if I am correct, the current accuracy is how HL1 also is, but I will double check.

**Comment by Combineadvisor** [comment]
Ah, That makes sense more sense now. thanks for the response

**Comment by DrVrej** [comment]
Apache now uses the exact spread from Half-Life 1, based on this value: https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/weapons.h#L423
