### ISSUE TITLE
Decay grunts

### ISSUE THREAD

**Issue by Combineadvisor** [VJ-HLR-Developers/Half-Life-Resurgence#66]
Since you have included the Half life and opposing force grunts, Is there any chance we will see the decay grunts?
![image](https://user-images.githubusercontent.com/77513716/127197731-8835edd7-7fa1-4326-9cc6-0ce0a3a582ba.png)

**Comment by DrVrej** [comment]
GitHub is meant for bug reports, enhancements, major questions or actual suggestions. Please don't post NPC requests on here.
