### ISSUE TITLE
-- SUGGESTION

### ISSUE THREAD

**Issue by BrainDeadperson** [VJ-HLR-Developers/Half-Life-Resurgence#69]
HLZE suggestion, a portion of mod now presumably discontinued, I suggest instead just porting everything to the main mod and keeping the models the same, and slap on some compatibility for the headcrab so it can latch onto scientists + guards just like in HLZE, use the current zombie skins and you might just have yourself a even better mod.

**Comment by Cpt-Hazama** [comment]
This is for bug reports only, stop posting useless threads
