### ISSUE TITLE
Combine Sniper Rifle lua error

### ISSUE THREAD

**Issue by stepa2** [VJ-HLR-Developers/Half-Life-Resurgence#72]
[Half-Life Resurgence] lua/weapons/weapon_vj_hlr2_csniper/shared.lua:101: attempt to index a nil value
  1. CustomOnThink - lua/weapons/weapon_vj_hlr2_csniper/shared.lua:101
   2. unknown - lua/weapons/weapon_vj_base/shared.lua:721

**Comment by DrVrej** [comment]
Can you please provide more info? An error alone is not very helpful.

**Comment by stepa2** [comment]
Error happens on dedicated server serverside when player holds the weapon.

**Comment by DrVrej** [comment]
Although I was not able to reproduce this error, I added a fail-safe in line 101 which should fix any errors from occurring.
Commit: c1ffd27201eef264877dc18b6f6daa0e56bd336d
