### ISSUE TITLE
(Sugesstion) Textures for Combine engineer and combine sniper as a skin for default model

### ISSUE THREAD

**Issue by jolopapina** [VJ-HLR-Developers/Half-Life-Resurgence#77]
Since the sniper and engineer are not textured as skins and do not have a separate model, this causes problems with dismemberment addons and with the BSMOD stun mod. The corpses of these soldiers are appearing as normal combines. This can be solved by adding the texture of the engineer and the sniper as a skin for default model, as with a shotgunner.

**Comment by DrVrej** [comment]
This would mean that we decompile the default Combine soldier model and add skins to it and then recompile it under a different directory/name to avoid overriding the default Combine soldier model. This is a lot of extra work for something that already works. I myself don't work with models, I am a programmer, but I doubt any modeler here would do this, so I will close this issue.
