### ISSUE TITLE
(SUGGESTION) Combine assassin voice

### ISSUE THREAD

**Issue by jolopapina** [VJ-HLR-Developers/Half-Life-Resurgence#78]
Voicelines like regular combines have. Example: https://steamcommunity.com/sharedfiles/filedetails/?id=2734988107

**Comment by DrVrej** [comment]
This post doesn't make sense, I have 0 idea what you are even trying to suggest.

**Comment by jolopapina** [comment]
Add voicelines to combine assassins. Is that clearer?

**Comment by DrVrej** [comment]
There is no combine assassin in HLR at the moment lol

**Comment by jolopapina** [comment]
oops. one second

**Comment by Cpt-Hazama** [comment]
The combine assassin doesn't need voicelines, afair that addon you linked doesnt even use actual sounds from the Half-Life universe. She's an assassin, she needs to be quiet just like the black ops assassins.

So no, we are not adding voicelines to the combine assassin
