### ISSUE TITLE
HLR NPCs does not reacts to trigger. 

### ISSUE THREAD

**Issue by bravosixgoingdark** [VJ-HLR-Developers/Half-Life-Resurgence#83]
In many parts of HL2, HLR NPCs just outright ignore the trigger. For instance, Barney never uses consoles to open doors, or Odessa Cabbage just holding a non existent RPG, rendering the campaign unplayable for me. I wonder if there is a conflicting addon/bug going on here. And do I have to post logs or something like here or not?

**Comment by Cpt-Hazama** [comment]
We are aware of this, though it is unfixable from our side. The campaign can be _mostly_ played all the way through, though we can not control scripted events that are designed for entirely different entities. We are limited to what we can do in Lua, if GMod's addons ran on C++ like Source engine then we could easily add support for the entire campaign

**Comment by bravosixgoingdark** [comment]
Oh damm, HLR really alleviates the perf hog that is the default NPCs. Too bad the scripted events are simply written in another language so that's a bummer.
