### ISSUE TITLE
[SUGGESTON] Combine dropship?

### ISSUE THREAD

**Issue by jolopapina** [VJ-HLR-Developers/Half-Life-Resurgence#85]
Can you add a working combine dropship? That deploys soldier, synths and do other thing they should do.

**Comment by DrVrej** [comment]
Appreciate the idea, but I don't take NPC suggestions, also reminder that GitHub isn't the appropriate place for requests.

**Comment by jolopapina** [comment]
What is appropriate place?

**Comment by Cpt-Hazama** [comment]
> 

He just said we DONT take requests, that means no where
