### ISSUE TITLE
The Gargantua Npc Keeps not shooting flames.

### ISSUE THREAD

**Issue by TheCelestial2000** [VJ-HLR-Developers/Half-Life-Resurgence#93]
The Gargantua only makes the sound of the flames but he keeps not shooting
And acts just like the baby version,
And controlling him can't use the flamethrower attack.

**Comment by DrVrej** [comment]
Barely any info is given here, but even if any issue like this existed, it should be fixed with the revamp version when it's out because the gargantua has been remade from scratch.
